import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { motion } from "framer-motion";
import styles from "../styles/Home.module.css";

export default function Id() {
  const {
    query: { id },
  } = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div className={styles.centerImage} layoutId={`image-${id}`}>
        <Image src={`/${id}.jpg`} alt="" width={752} height={423} />
      </motion.div>
      <motion.h1 layoutId={`title-${id}`} className={styles.pageTitle}>
        Image {id}
      </motion.h1>
      <p className={styles.paragraph}>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua.
      </p>
      <p className={styles.paragraph}>
        minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
        ex ea commodo consequat.
      </p>
      <p className={styles.paragraph}>
        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum
        dolore eu fugiat nulla pariatur.
      </p>
      <p className={styles.paragraph}>
        Excepteur sint occaecat cupidatat non proident, sunt in culpa qui
        officia deserunt mollit anim id est laborum.
      </p>
    </div>
  );
}
