import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.topTitle}>Home</h1>
      {[...Array(3)].map((_, i) => (
        <Link href={`/${i}`} key={i}>
          <a className={styles.image}>
            <motion.div
              layoutId={`image-${i}`}
            >
              <Image src={`/${i}.jpg`} alt="" width={368} height={207} />
            </motion.div>
            <motion.h2 layoutId={`title-${i}`} className={styles.imageName}>
              Image {i}
            </motion.h2>
          </a>
        </Link>
      ))}
    </div>
  );
}
